### ISSUE TITLE
momd increases memory unrelated to ousage.

### ISSUE THREAD

**Issue by gangrif** [aglitke/mom#1]
I've been attempting to use MoM on a Fedora 14 system, with a Fedora 14 KVM Guest. 

I have momd running on the host, with the default set of balloon rules. 

I have momd confiugured to check the guest via the momd-guest network daemon. 

Momd is able to talke to the guest, but it's apparently not getting the proper response, because it just balloons the guest's memory right up to its maximum, regardless of how much memory is in use on the guest. 

I realize that this may be the wrong place to submit this sort of thing, it may be more of a help request than a bug, but i was not able to find any documentation other than the wiki here at github.

**Comment by aglitke** [comment]
Hi gangrif,

The default ballooning rules are designed to balloon guests downward only when the host is under memory pressure.  What does your /proc/meminfo look like when you are expecting MOM to balloon your guest?

**Comment by gangrif** [comment]
With my vm's currentmemory set to 1gb and max memory set to 2gb. 

Before startig up mom-guestd, top shows me a little over 500mb of free memory. 
/proc/meminfo shows the same.  1gb total, ~500mb free

Starting mom-guestd, with momd already running on my host, immediately starts the process of expanding memory on my guest.  
The log on my host reads entries like this one:

Results: [0.2, 0.05, 0.05, 0.05, 0.0025, 'change_big_enough', 'shrink_guest', 'grow_guest', 0.5135729117573401, [None]]
2011-02-16 14:31:20,424 - mom.Controllers.Balloon - INFO - Ballooning guest:13 from 1508352 to 1583769

They continue until the maximum memory limit for my guest is reached. (2gb), at which point top, and proc/meminfo both show 2gb of memory, and 1.5gb free. 

Then the log changes its entries slightly, to:

Results: [0.2, 0.05, 0.05, 0.05, 0.0025, 'change_big_enough', 'shrink_guest', 'grow_guest', 0.5120412018623068, [0]]
(note, the last column says "0" where in the previous entries it said "None"

**Comment by aglitke** [comment]
Okay.  This confirms my original theory.  The results line "[0.2, 0.05, 0.05, 0.05, 0.0025, 'change_big_enough', 'shrink_guest', 'grow_guest', 0.5135729117573401, [None]]" tells me a few things:
1. From item #1: Your host target memory pressure is set to 20%.  This means that these rules will deflate guest balloons until the amount of host free memory drops below 20%.
2. From item #9: Your host has over 51% free memory remaining.
3. The policy has determined that your host has plenty of free memory and decides to call grow_guest() for all of your guests.

The default policy strives to give guests as much memory as it can so long as the host is not under too much memory pressure.  If you want to see MOM leave the guests ballooned, you could try setting 'pressure_threshold' in your policy file to 0.50.

Is there a reason you want to keep your VMs ballooned down to half of their allowable size?

**Comment by gangrif** [comment]
I guess i just imagined that it worked as such.  The VM would be left alone until it needed more memory.  now that you explain it though, it makes sense.  Why limit the VM if there's free memory.  

So, if my host were running out of memory, the guests would be scaled back?  

Thanks, by the way, for the fast responses. 

This is a test system, if it works out well, it may be applied to a larger install at the institution i work at. We have a RedHat Cluster running KVM.

**Comment by aglitke** [comment]
No problem, I am glad to help.

MOM is designed to let you specify your own policy file so if you were so inclined you could modify the algorithm to your specific needs.  I am spending quite a bit of time researching ballooning strategies myself.

**Comment by gangrif** [comment]
It seems that KVM takes the approach of granting the lower limit at vm creation, allowing you to balloon up to the maximum.  Which is why i thought MOM took the same approach.
